const fonts = {
    "displayLarge": {
        "fontFamily": "Roboto",
        "fontSize": 57,
        "fontWeight": "700",
        "letterSpacing": 0,
        "lineHeight": 64,
    },
    "displayMedium": {
        "fontFamily": "Roboto",
        "fontSize": 45,
        "fontWeight": "700",
        "letterSpacing": 0,
        "lineHeight": 52,
    },
    "displaySmall": {
        "fontFamily": "Roboto",
        "fontSize": 36,
        "fontWeight": "700",
        "letterSpacing": 0,
        "lineHeight": 44,
    },
    "headlineLarge": {
        "fontFamily": "Roboto",
        "fontSize": 32,
        "fontWeight": "700",
        "letterSpacing": 0,
        "lineHeight": 40,
    },
    "headlineMedium": {
        "fontFamily": "Roboto",
        "fontSize": 28,
        "fontWeight": "700",
        "letterSpacing": 0,
        "lineHeight": 36,
    },
    "headlineSmall": {
        "fontFamily": "Roboto",
        "fontSize": 24,
        "fontWeight": "700",
        "letterSpacing": 0,
        "lineHeight": 32,
    },
    "titleLarge": {
        "fontFamily": "Roboto",
        "fontSize": 22,
        "fontWeight": "700",
        "letterSpacing": 0,
        "lineHeight": 28,
    },
    "titleMedium": {
        "fontFamily": "Roboto",
        "fontSize": 16,
        "fontWeight": "500",
        "letterSpacing": 0.15,
        "lineHeight": 24,
    },
    "titleSmall": {
        "fontFamily": "Roboto",
        "fontSize": 14,
        "fontWeight": "500",
        "letterSpacing": 0.1,
        "lineHeight": 20,
    },
    "labelLarge": {
        "fontFamily": "Roboto",
        "fontSize": 14,
        "fontWeight": "500",
        "letterSpacing": 0.1,
        "lineHeight": 20,
    },
    "labelMedium": {
        "fontFamily": "Roboto",
        "fontSize": 12,
        "fontWeight": "500",
        "letterSpacing": 0.5,
        "lineHeight": 16,
    },
    "labelSmall": {
        "fontFamily": "Roboto",
        "fontSize": 11,
        "fontWeight": "500",
        "letterSpacing": 0.5,
        "lineHeight": 16,
    },
    "bodyLarge": {
        "fontFamily": "Roboto",
        "fontSize": 16,
        "fontWeight": "400",
        "letterSpacing": 0.15,
        "lineHeight": 24,
    },
    "bodyMedium": {
        "fontFamily": "Roboto",
        "fontSize": 14,
        "fontWeight": "400",
        "letterSpacing": 0.25,
        "lineHeight": 20,

    },
    "bodySmall": {
        "fontFamily": "Roboto",
        "fontSize": 12,
        "fontWeight": "400",
        "letterSpacing": 0.4,
        "lineHeight": 16,
    },
    "default": {
        "fontFamily": "Roboto",
        "fontSize": 14,
        "fontWeight": "400",
        "letterSpacing": 0.25,
        "lineHeight": 20,
    },
    "tabNavigation": {
        "fontFamily": "Roboto",
        "fontSize": 13,
        "fontWeight": "400",
        "letterSpacing": 0.25,
        "lineHeight": 20,
    },
};

export default fonts