import { MD3LightTheme, configureFonts } from 'react-native-paper';

const fontConfig = {
    "displayLarge": {
        "fontFamily": "Roboto",
        "fontSize": 57,
        "fontWeight": "700",
        "letterSpacing": 0,
        "lineHeight": 64,
    },
    "displayMedium": {
        "fontFamily": "Roboto",
        "fontSize": 45,
        "fontWeight": "400",
        "letterSpacing": 0,
        "lineHeight": 52,
    },
    "displaySmall": {
        "fontFamily": "Roboto",
        "fontSize": 36,
        "fontWeight": "400",
        "letterSpacing": 0,
        "lineHeight": 44,
    },
    "headlineLarge": {
        "fontFamily": "Roboto",
        "fontSize": 32,
        "fontWeight": "400",
        "letterSpacing": 0,
        "lineHeight": 40,
    },
    "headlineMedium": {
        "fontFamily": "Roboto",
        "fontSize": 28,
        "fontWeight": "400",
        "letterSpacing": 0,
        "lineHeight": 36,
    },
    "headlineSmall": {
        "fontFamily": "Roboto",
        "fontSize": 24,
        "fontWeight": "400",
        "letterSpacing": 0,
        "lineHeight": 32,
    },
    "titleLarge": {
        "fontFamily": "Roboto",
        "fontSize": 22,
        "fontWeight": "500",
        "letterSpacing": 0,
        "lineHeight": 28,
    },
    "titleMedium": {
        "fontFamily": "Roboto",
        "fontSize": 16,
        "fontWeight": "500",
        "letterSpacing": 0.15,
        "lineHeight": 24,
    },
    "titleSmall": {
        "fontFamily": "Roboto",
        "fontSize": 14,
        "fontWeight": "500",
        "letterSpacing": 0.1,
        "lineHeight": 20,
    },
    "labelLarge": {
        "fontFamily": "Roboto",
        "fontSize": 14,
        "fontWeight": "500",
        "letterSpacing": 0.1,
        "lineHeight": 20,
    },
    "labelMedium": {
        "fontFamily": "Roboto",
        "fontSize": 12,
        "fontWeight": "500",
        "letterSpacing": 0.5,
        "lineHeight": 16,
    },
    "labelSmall": {
        "fontFamily": "Roboto",
        "fontSize": 11,
        "fontWeight": "500",
        "letterSpacing": 0.5,
        "lineHeight": 16,
    },
    "bodyLarge": {
        "fontFamily": "Roboto",
        "fontSize": 16,
        "fontWeight": "400",
        "letterSpacing": 0.15,
        "lineHeight": 24,
    },
    "bodyMedium": {
        "fontFamily": "Roboto",
        "fontSize": 14,
        "fontWeight": "400",
        "letterSpacing": 0.25,
        "lineHeight": 20,
    },
    "bodySmall": {
        "fontFamily": "Roboto",
        "fontSize": 12,
        "fontWeight": "400",
        "letterSpacing": 0.4,
        "lineHeight": 16,
    },
    "default": {
        "fontFamily": "Roboto",
        "fontSize": 14,
        "fontWeight": "400",
        "letterSpacing": 0.25,
        "lineHeight": 20,
    },
};

const theme = {
    ...MD3LightTheme,
    "fonts": configureFonts({ config: fontConfig }),
    "colors": {
        "primary": "#E7AB3C",
        "onPrimary": "rgb(255, 255, 255)",
        "primaryContainer": "rgb(255, 222, 172)",
        "onPrimaryContainer": "rgb(40, 25, 0)",
        "secondary": "rgb(110, 92, 64)",
        "onSecondary": "rgb(255, 255, 255)",
        "secondaryContainer": "rgb(248, 223, 187)",
        "onSecondaryContainer": "rgb(38, 25, 4)",
        "tertiary": "rgb(78, 101, 66)",
        "onTertiary": "rgb(255, 255, 255)",
        "tertiaryContainer": "rgb(208, 234, 191)",
        "onTertiaryContainer": "rgb(13, 32, 5)",
        "error": "rgb(186, 26, 26)",
        "onError": "rgb(255, 255, 255)",
        "errorContainer": "rgb(255, 218, 214)",
        "onErrorContainer": "rgb(65, 0, 2)",
        "background": "rgb(255, 255, 255)",
        "onBackground": "rgb(31, 27, 22)",
        "surface": "rgb(255, 255, 255)",
        "onSurface": "rgb(31, 27, 22)",
        "surfaceVariant": "rgb(239, 224, 207)",
        "onSurfaceVariant": "rgb(78, 69, 57)",
        "outline": "rgb(128, 117, 103)",
        "outlineVariant": "rgb(210, 197, 180)",
        "shadow": "rgb(0, 0, 0)",
        "scrim": "rgb(0, 0, 0)",
        "inverseSurface": "rgb(52, 48, 42)",
        "inverseOnSurface": "rgb(248, 239, 231)",
        "inversePrimary": "rgb(251, 188, 73)",
        "elevation": {
            "level0": "transparent",
            "level1": "rgb(249, 243, 242)",
            "level2": "rgb(245, 238, 235)",
            "level3": "rgb(241, 233, 227)",
            "level4": "rgb(240, 231, 224)",
            "level5": "rgb(237, 228, 219)"
        },
        "surfaceDisabled": "rgba(31, 27, 22, 0.12)",
        "onSurfaceDisabled": "rgba(31, 27, 22, 0.38)",
        "backdrop": "rgba(55, 47, 36, 0.4)"
    }
}

export default theme